module.exports.coffeePods = [
    {
      name: 'CP001',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'CP003',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'CP011',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'CP013',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'CP021',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_PSL',
    },
    {
      name: 'CP023',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_PSL',
    },
    {
      name: 'CP031',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_MOCHA',
    },
    {
      name: 'CP033',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_MOCHA',
    },
    {
      name: 'CP041',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT',
    },
    {
      name: 'CP043',
      product_type: 'COFFEE_POD_SMALL',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT',
    }, {
      name: 'CP101',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'CP103',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'CP111',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'CP113',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'CP121',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_PSL',
    },
    {
      name: 'CP123',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_PSL',
    },
    {
      name: 'CP131',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_MOCHA',
    },
    {
      name: 'CP133',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_MOCHA',
    },
    {
      name: 'CP141',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 1,
      coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT',
    },
    {
      name: 'CP143',
      product_type: 'COFFEE_POD_LARGE',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_HAZELNUT',
    },
    {
      name: 'EP003',
      product_type: 'ESPRESSO_POD',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'EP005',
      product_type: 'ESPRESSO_POD',
      pack_size: 5,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'EP007',
      product_type: 'ESPRESSO_POD',
      pack_size: 7,
      coffee_flavor: 'COFFEE_FLAVOR_VANILLA',
    },
    {
      name: 'EP013',
      product_type: 'ESPRESSO_POD',
      pack_size: 3,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'EP015',
      product_type: 'ESPRESSO_POD',
      pack_size: 5,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
    {
      name: 'EP017',
      product_type: 'ESPRESSO_POD',
      pack_size: 7,
      coffee_flavor: 'COFFEE_FLAVOR_CARAMEL',
    },
  ];
  
  module.exports.coffeeMachines = [
    {
      name: 'CM001',
      model: 'base',
      product_type: 'COFFEE_MACHINE_SMALL',
    },
    {
      name: 'CM002',
      model: 'premium',
      product_type: 'COFFEE_MACHINE_SMALL',
    },
    {
      name: 'CM003',
      model: 'deluxe',
      product_type: 'COFFEE_MACHINE_SMALL',
      water_line_compatible: true,
    },
    {
      name: 'CM101',
      model: 'base',
      product_type: 'COFFEE_MACHINE_LARGE',
    },
    {
      name: 'CM102',
      model: 'premium',
      product_type: 'COFFEE_MACHINE_LARGE',
      water_line_compatible: true,
    },
    {
      name: 'CM103',
      model: 'deluxe',
      product_type: 'COFFEE_MACHINE_LARGE',
      water_line_compatible: true,
    },
    {
      name: 'EM001',
      model: 'base',
      product_type: 'ESPRESSO_MACHINE',
    },
    {
      name: 'EM002',
      model: 'premium',
      product_type: 'ESPRESSO_MACHINE',
    },
    {
      name: 'EM003',
      model: 'deluxe',
      product_type: 'ESPRESSO_MACHINE',
      water_line_compatible: true,
    },
  ];